export enum RIDE_STATUS {
  REQUESTED = 'REQUESTED',
  RIDE_REQUESTED = 'REQUESTED',
  SEARCHING_DRIVER = 'SEARCHING_DRIVER',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  DRIVER_ARRIVING = 'DRIVER_ARRIVING',
  DRIVER_ARRIVED = 'DRIVER_ARRIVED',
  RIDE_STARTED = 'RIDE_STARTED',
  RIDE_COMPLETED = 'RIDE_COMPLETED',
  CANCELLED_BY_PASSENGER = 'CANCELLED_BY_PASSENGER',
  CANCELLED_BY_DRIVER = 'CANCELLED_BY_DRIVER',
  NO_DRIVER_FOUND = 'NO_DRIVER_FOUND',
}

export enum VehicleType {
  BIKE = 'bike',
  AUTO = 'auto',
  CAR = 'car',
  SUV = 'suv',
}

export enum PaymentMethod {
  CASH = 'cash',
  ONLINE = 'online',
}

export const CANCELLABLE_STATUSES = [
  RIDE_STATUS.REQUESTED,
  RIDE_STATUS.SEARCHING_DRIVER,
  RIDE_STATUS.DRIVER_ASSIGNED,
  RIDE_STATUS.DRIVER_ARRIVING,
  RIDE_STATUS.DRIVER_ARRIVED,
];

export const VEHICLE_TYPES = Object.values(VehicleType);
export const PAYMENT_METHOD = Object.values(PaymentMethod);
