const ROLES = Object.freeze({
  PASSENGER: "passenger",
  DRIVER: "driver",
});

const RIDE_STATUS = Object.freeze({
  REQUESTED: "REQUESTED",
  SEARCHING_DRIVER: "SEARCHING_DRIVER",
  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",
  DRIVER_ARRIVING: "DRIVER_ARRIVING",
  DRIVER_ARRIVED: "DRIVER_ARRIVED",
  RIDE_STARTED: "RIDE_STARTED",
  RIDE_COMPLETED: "RIDE_COMPLETED",
  CANCELLED_BY_PASSENGER: "CANCELLED_BY_PASSENGER",
  CANCELLED_BY_DRIVER: "CANCELLED_BY_DRIVER",
  NO_DRIVER_FOUND: "NO_DRIVER_FOUND",
});

// Ride statuses from which each role is allowed to cancel
const CANCELLABLE_STATUSES = Object.freeze([
  RIDE_STATUS.REQUESTED,
  RIDE_STATUS.SEARCHING_DRIVER,
  RIDE_STATUS.DRIVER_ASSIGNED,
  RIDE_STATUS.DRIVER_ARRIVING,
  RIDE_STATUS.DRIVER_ARRIVED,
]);

const VEHICLE_TYPES = Object.freeze(["bike", "auto", "car", "suv"]);

const PAYMENT_METHOD = Object.freeze({
  CASH: "cash",
  ONLINE: "online",
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
});

const GENDER = Object.freeze({
  MALE: "male",
  FEMALE: "female",
  OTHER: "other",
  PREFER_NOT_TO_SAY: "prefer_not_to_say",
});

const SOS_STATUS = Object.freeze({
  TRIGGERED: "TRIGGERED",
  ACKNOWLEDGED: "ACKNOWLEDGED",
  RESOLVED: "RESOLVED",
});

const NOTIFICATION_TYPE = Object.freeze({
  RIDE_REQUESTED: "RIDE_REQUESTED",
  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",
  DRIVER_ARRIVING: "DRIVER_ARRIVING",
  DRIVER_ARRIVED: "DRIVER_ARRIVED",
  RIDE_STARTED: "RIDE_STARTED",
  RIDE_COMPLETED: "RIDE_COMPLETED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  RIDE_CANCELLED: "RIDE_CANCELLED",
  SOS_TRIGGERED: "SOS_TRIGGERED",
  RATING_RECEIVED: "RATING_RECEIVED",
});

module.exports = {
  ROLES,
  RIDE_STATUS,
  CANCELLABLE_STATUSES,
  VEHICLE_TYPES,
  PAYMENT_METHOD,
  PAYMENT_STATUS,
  GENDER,
  SOS_STATUS,
  NOTIFICATION_TYPE,
};
